//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Character
{
	protected string name;

	protected byte level;

	public virtual string Level
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

	public Character(string name, byte level)
	{
	}

	public virtual string ToString()
	{
		throw new System.NotImplementedException();
	}

}

