//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class NonPlayerCharacter : Character
{
	protected bool isActive;

	public virtual bool IsActive
	{
		get;
		set;
	}

	public NonPlayerCharacter(string name, byte level, bool isActive)
	{
	}

	public override string ToString()
	{
		throw new System.NotImplementedException();
	}

}

