//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Player : Character
{
	protected TimeSpan gameTime;

	public virtual TimeSpan GameTime
	{
		get;
		set;
	}

	public Player(string name, byte level, TimeSpan gameTime)
	{
	}

	public override string ToString()
	{
		throw new System.NotImplementedException();
	}

}

